# Generated by Django 5.1.6 on 2025-02-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='connection_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='gpu_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='is_charging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='is_first_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='is_touchscreen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='ram_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
